### ISSUE TITLE
❌ Depecrated module

### ISSUE THREAD

**Issue by MasterCruelty** [Norelec91/norelecbot#1]
I've seen you used at least one time the <code>telepot</code> module to interact with the Telegram API.
It's deprecated so I suggest you to choose another library.

```ruby 
import telepot
```

**Comment by Norelec91** [comment]
Hello,

I know but this project is abandoned, sorry :(

**Comment by MasterCruelty** [comment]
> Hello,
> 
> I know but this project is abandoned, sorry :(

Ok don't worry. I'll close then
